### PR TITLE
feat: import extism functions from `extism:host/env`

### PR DESCRIPTION
**Pull request by mhmd-azeez**
This part of the extism/extism/issues/504 effort to move extism functions to `extism::env`. I have tested this with a modified go-sdk

### CODE REVIEW

**Comment by mhmd-azeez** [comment]
Ah, it seems like I have misread it as `extism::env`. will push a fix

**Comment by mhmd-azeez** [comment]
The tests are expected to fail until the runtimes are updated to support the new namespace

**Comment by zshipko** [comment]
@mhmd-azeez the runtimes have been updated, does this need some additional changes still?

**Comment by mhmd-azeez** [comment]
@zshipko fixed the tests, feel free to merge the PR

**Pull request merged**
